# Generated by Django 5.0.6 on 2024-06-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flippingmanager', '0002_alter_purchase_category_alter_purchase_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='purchase',
            field=models.ForeignKey(limit_choices_to={'sale__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='flippingmanager.purchase'),
        ),
    ]
